/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartac;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author my pc
 */
public class Control extends javax.swing.JFrame {

    /**
     * Creates new form Control
     */
    int angkaa1 = 0;
    private AC tes;
    int tis;
    Termo termo = new Termo();

    public Control() {
        initComponents();
        currentdate();
        tes = new AC();
        this.setLocationRelativeTo(null);
    }

    /**
     * ue This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        angka2 = new javax.swing.JTextField();
        angka = new javax.swing.JTextField();
        Sav3nPl4y = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        UpPeople = new javax.swing.JButton();
        UpSuhu = new javax.swing.JButton();
        DownPeople = new javax.swing.JButton();
        DownSuhu = new javax.swing.JButton();
        ON = new javax.swing.JButton();
        OFF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Help = new javax.swing.JPanel();
        AboutUs = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remote");
        setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        angka2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        angka2.setText("0");
        angka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka2ActionPerformed(evt);
            }
        });
        getContentPane().add(angka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        angka.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        angka.setText("26");
        angka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaActionPerformed(evt);
            }
        });
        getContentPane().add(angka, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        Sav3nPl4y.setBackground(new java.awt.Color(255, 255, 255));
        Sav3nPl4y.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Play.png"))); // NOI18N
        Sav3nPl4y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sav3nPl4yMouseClicked(evt);
            }
        });
        Sav3nPl4y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sav3nPl4yActionPerformed(evt);
            }
        });
        getContentPane().add(Sav3nPl4y, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 80, 60));

        jLabel1.setText("JUMLAH MANUSIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 89, -1, -1));

        jLabel2.setText("SUHU YANG DI KELUARKAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 120, 19));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, 20));

        UpPeople.setBackground(new java.awt.Color(255, 255, 255));
        UpPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Up.png"))); // NOI18N
        UpPeople.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpPeopleMouseClicked(evt);
            }
        });
        UpPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpPeopleActionPerformed(evt);
            }
        });
        getContentPane().add(UpPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 70));

        UpSuhu.setBackground(new java.awt.Color(255, 255, 255));
        UpSuhu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Up.png"))); // NOI18N
        UpSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpSuhuActionPerformed(evt);
            }
        });
        getContentPane().add(UpSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 120, 70));

        DownPeople.setBackground(new java.awt.Color(255, 255, 255));
        DownPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Down.png"))); // NOI18N
        DownPeople.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DownPeopleMouseClicked(evt);
            }
        });
        DownPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownPeopleActionPerformed(evt);
            }
        });
        getContentPane().add(DownPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 70));

        DownSuhu.setBackground(new java.awt.Color(255, 255, 255));
        DownSuhu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Down.png"))); // NOI18N
        DownSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownSuhuActionPerformed(evt);
            }
        });
        getContentPane().add(DownSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 110, 70));

        ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Bon.jpg"))); // NOI18N
        ON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ONMouseClicked(evt);
            }
        });
        ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONActionPerformed(evt);
            }
        });
        getContentPane().add(ON, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 80, 80));

        OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/boff.jpg"))); // NOI18N
        OFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OFFMouseClicked(evt);
            }
        });
        OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFFActionPerformed(evt);
            }
        });
        getContentPane().add(OFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 80, 80));

        jLabel3.setText("o");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 10, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("C");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLabel5.setText("Suhu Ruangan Aktif");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, 20));
        getContentPane().add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 330));
        getContentPane().add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 330));

        pack();
    }// </editor-fold>                        

    private void Sav3nPl4yActionPerformed(java.awt.event.ActionEvent evt) {                                          
        termo.getjLabel1().setText(angka.getText());
        termo.setVisible(true);
        OFF.setVisible(true);
        ON.setVisible(false);
        tes.setVisible(true);
        new AC().resize(250, 150);
        jLabel5.setVisible(false);
        String dbtime;
        String dbdate;
        String dbsuhu;
        String dbmanusia;

        dbtime = time.getText();
        dbdate = date.getText();
        dbsuhu = angka.getText();
        dbmanusia = angka2.getText();

        Integer.parseInt(dbsuhu);
        Integer.parseInt(dbmanusia);

        Db D = new Db();
        D.query("insert into data values ('" + dbdate + "','" + dbtime + "'," + dbsuhu + "," + dbmanusia + ")");
        //JOptionPane.showMessageDialog(null, "Data Tersimpan. ");
    }                                         

    private void DownPeopleActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        if ((angka2.getText().equals("0"))) {
//            angka2.setText("" + angkaa1);
//            //JOptionPane.showMessageDialog(null, "suhu minimum");
//        } else {
//            angkaa1 = Integer.parseInt(angka2.getText(), 10);
//            angkaa1 = angkaa1 - 1;
//            angka2.setText("" + angkaa1);
//        }
//        String angkaaa = angka2.getText();
//        Integer angkaaa1 = Integer.parseInt(angkaaa, 10);
//        angkaaa1 = angkaaa1 - 1;
//        angka2.setText(angkaaa1.toString());

        // TODO add your handling code here:
    }                                          

    private void UpSuhuActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:

        if ("30".equals(angka.getText())) {
            angka.setText("" + angkaa1);
            //JOptionPane.showMessageDialog(null, "suhu maksimum");
        } else {
            angkaa1 = Integer.parseInt(angka.getText(), 10);
            angkaa1 = angkaa1 + 1;
            angka.setText("" + angkaa1);
        }
    }                                      

    private void ONActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void ONMouseClicked(java.awt.event.MouseEvent evt) {                                
        OFF.setVisible(true);
        ON.setVisible(false);
        tes.setVisible(true);
        jLabel5.setVisible(false);
        new AC().resize(250, 150);
        termo.getjLabel1().setText(angka.getText());
        termo.setVisible(true);
        termo.resize(150, 150);

        // TODO add your handling code here:
    }                               

    private void UpPeopleActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String angkaaa = angka2.getText();
        Integer angkaaa1 = Integer.parseInt(angkaaa, 10);
        angkaaa1 = angkaaa1 + 1;
        angka2.setText(angkaaa1.toString());
// TODO add your handling code here:
    }                                        

    private void DownSuhuActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if ("18".equals(angka.getText())) {
            angka.setText("" + angkaa1);
            //JOptionPane.showMessageDialog(null, "suhu minimum");
        } else {
            angkaa1 = Integer.parseInt(angka.getText(), 10);
            angkaa1 = angkaa1 - 1;
            angka.setText("" + angkaa1);
        }
        // TODO add your handling code here:
    }                                        

    private void OFFMouseClicked(java.awt.event.MouseEvent evt) {                                 
        ON.setVisible(true);
        OFF.setVisible(false);
        tes.dispose();
        angka.setText("26");
        angka2.setText("0");
        jLabel5.setVisible(true);
        // TODO add your handling code here:
    }                                

    private void OFFActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void UpPeopleMouseClicked(java.awt.event.MouseEvent evt) {                                      
        if (evt.getClickCount() == 3) {
            tes.setVisible(true);
            ON.setVisible(false);
            OFF.setVisible(true);
            jLabel5.setVisible(false);
            tes.setVisible(true);
            String angkaa = angka.getText();
            Integer angkaa1 = Integer.parseInt(angkaa, 10);
            angkaa1 = angkaa1 - 1;
            angka.setText(angkaa1.toString());
            termo.getjLabel1().setText(angka.getText());
            termo.setVisible(true);
            termo.resize(150, 150);
        }
        // TODO add your handling code here:
    }                                     

    private void angka2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        angka2.setText(null);
        // TODO add your handling code here:
    }                                      

    private void angkaActionPerformed(java.awt.event.ActionEvent evt) {                                      
        angka.setText("27");
        // TODO add your handling code here:
    }                                     

    private void Sav3nPl4yMouseClicked(java.awt.event.MouseEvent evt) {                                       

        // TODO add your handling code here:
    }                                      

    private void DownPeopleMouseClicked(java.awt.event.MouseEvent evt) {                                        
        if (evt.getClickCount() == 3) {
            tes.setVisible(true);
            ON.setVisible(false);
            OFF.setVisible(true);
            jLabel5.setVisible(false);
            tes.setVisible(true);
            String angkaa = angka.getText();
            Integer angkaa1 = Integer.parseInt(angkaa, 10);
            angkaa1 = angkaa1 + 1;
            angka.setText(angkaa1.toString());
            termo.getjLabel1().setText(angka.getText());
            termo.setVisible(true);
            termo.resize(150, 150);
            
        }
        if ((angka2.getText().equals("0"))) {
            angka2.setText("" + angkaa1);
            ON.setVisible(true);
            OFF.setVisible(false);
            tes.dispose();
            angka.setText("26");
            jLabel5.setVisible(true);
            termo.getjLabel1().setText("26");
            //JOptionPane.showMessageDialog(null, "suhu minimum");
        } else {
            angkaa1 = Integer.parseInt(angka2.getText(), 10);
            angkaa1 = angkaa1 - 1;
            angka2.setText("" + angkaa1);
        }
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel AboutUs;
    private javax.swing.JButton DownPeople;
    private javax.swing.JButton DownSuhu;
    private javax.swing.JPanel Help;
    private javax.swing.JButton OFF;
    private javax.swing.JButton ON;
    private javax.swing.JButton Sav3nPl4y;
    private javax.swing.JButton UpPeople;
    private javax.swing.JButton UpSuhu;
    private javax.swing.JTextField angka;
    private javax.swing.JTextField angka2;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel time;
    // End of variables declaration                   

    public void currentdate() {
        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();

                    int mo = cal.get(Calendar.MONTH);
                    int ye = cal.get(Calendar.YEAR);
                    int d = cal.get(Calendar.DAY_OF_MONTH);
                    date.setText(+d + " - " + (mo + 1) + " - " + ye);

                    int se = cal.get(Calendar.SECOND);
                    int min = cal.get(Calendar.MINUTE);
                    int ha = cal.get(Calendar.HOUR);
                    time.setText(+ha + " : " + (min) + " : " + se);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SmartAC.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        };
        clock.start();
    }
}
